(package "ffmpeg-player"
         "0.2.1"
         "Play video using ffmpeg")

(website-url "https://github.com/jcs-elpa/ffmpeg-player")
(keywords "video" "ffmpeg" "buffering" "images")

(package-file "ffmpeg-player.el")

(source "melpa")

(depends-on "emacs" "24.4")
(depends-on "s")
(depends-on "f")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
